# theme: modernist
remote_theme: pages-themes/modernist@v0.2.0
title: "seafloorsegue.net"
description: "My (Henry's) personal website where I make blog posts instead of posting on social media"
author: "@henry.pfc | @Hexkel"

show_downloads: false

plugins:
- jekyll-remote-theme
