# theme: modernist
remote_theme: pages-themes/modernist@v0.2.0
title: "seafloorsegue.net"
description: "Henry's personal website"
author: "@henry.pfc | @Hexkel"

show_downloads: false

plugins:
- jekyll-remote-theme






