# theme: modernist
remote_theme: pages-themes/modernist@v0.2.0
title: "seafloorsegue.net"
description: "My (Henry's) personal blog"
author: "Henry"

show_downloads: false

plugins:
- jekyll-remote-theme

